spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://101.201.150.196:3306/dfyp_boc?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 20151127
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
#  redis:
#    host: 101.201.150.196 # Redis服务器地址
#    database: 0 # Redis数据库索引（默认为0）
#    port: 6379 # Redis服务器连接端口
#    password: dfyp123 # Redis服务器连接密码（默认为空）
#    timeout: 30000ms # 连接超时时间（毫秒）
#    lettuce:
#      pool:
#        max-idle: 100
#        max-active: 100
#        min-idle: 20
logging:
  path: /var/logs #配置日志生成路径

#文件上传 下载配置信息
file:
  path:
    download: http://www.yapinmall.com/third/
    upload: /app/fileServer/third

#上传文件到文件服务器的配置   待确认
ftpconfig:
  #IP
  host: 123.124.191.195
  #端口
  port: 988
  user: DFYP
  password: 49203a6a2de0427cb48e7a87d35eea50
  basePath: upload
  #源文件目录地址
  sourceFile: /sourceFile